package main

// Paqet (https://github.com/hanselime/paqet) is a raw-packet proxy: it
// crafts and captures TCP packets directly with pcap, bypassing the host's
// own TCP/IP stack and connection tracking, and carries KCP+smux on top for
// a fast, reliable, encrypted, multiplexed transport. That's a genuinely
// different engine from rmtunnel's own protocol.go — not something to
// reimplement here, so this wraps the real paqet binary instead: download
// it, generate its own YAML config from a guided wizard, and manage it as
// its own systemd service, alongside rmtunnel's native tunnels in the same
// "Manage tunnels" screen.
//
// paqet's own role naming doesn't match rmtunnel's Role: paqet's "client"
// is the side with socks5/forward — i.e. the box exposing ports to real
// users — and it's also the side that dials out first. paqet's "server" is
// the side being dialed, which is also where the real backend lives. So a
// paqet tunnel is inherently shaped like rmtunnel's Direction "direct": the
// ports-owning side initiates. See docs on Direction in config.go.

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	paqetRepoOwner = "hanselime"
	paqetRepoName  = "paqet"
	paqetBinPath   = "/usr/local/bin/paqet"
)

// --- config schema (mirrors paqet's own YAML — see conf.go in its source) -

type paqetLog struct {
	Level string `yaml:"level"`
}

type paqetListen struct {
	Addr string `yaml:"addr"`
}

type paqetSocks5 struct {
	Listen   string `yaml:"listen"`
	Username string `yaml:"username,omitempty"`
	Password string `yaml:"password,omitempty"`
}

type paqetForward struct {
	Listen   string `yaml:"listen"`
	Target   string `yaml:"target"`
	Protocol string `yaml:"protocol"`
}

type paqetAddr struct {
	Addr      string `yaml:"addr"`
	RouterMAC string `yaml:"router_mac"`
}

type paqetTCP struct {
	LocalFlag  []string `yaml:"local_flag,omitempty"`
	RemoteFlag []string `yaml:"remote_flag,omitempty"`
}

type paqetPCAP struct {
	Sockbuf int `yaml:"sockbuf,omitempty"`
}

type paqetNetwork struct {
	Interface string     `yaml:"interface"`
	GUID      string     `yaml:"guid,omitempty"`
	IPv4      paqetAddr  `yaml:"ipv4"`
	TCP       paqetTCP   `yaml:"tcp"`
	PCAP      *paqetPCAP `yaml:"pcap,omitempty"`
}

type paqetServerAddr struct {
	Addr string `yaml:"addr"`
}

// paqetKCP mirrors paqet's transport.kcp block. NoDelay/Interval/Resend/
// NoCongestion/WDelay/AckNoDelay are pointers so they're only emitted for
// mode "manual" — paqet derives them from named presets (normal/fast/
// fast2/fast3) internally otherwise, and 0/false are meaningful values that
// omitempty on a plain int/bool would wrongly drop.
type paqetKCP struct {
	Mode         string `yaml:"mode"`
	NoDelay      *int   `yaml:"nodelay,omitempty"`
	Interval     *int   `yaml:"interval,omitempty"`
	Resend       *int   `yaml:"resend,omitempty"`
	NoCongestion *int   `yaml:"nocongestion,omitempty"`
	WDelay       *bool  `yaml:"wdelay,omitempty"`
	AckNoDelay   *bool  `yaml:"acknodelay,omitempty"`

	MTU    int `yaml:"mtu,omitempty"`
	Rcvwnd int `yaml:"rcvwnd,omitempty"`
	Sndwnd int `yaml:"sndwnd,omitempty"`
	Dshard int `yaml:"dshard,omitempty"` // FEC data shards, 0 = FEC disabled
	Pshard int `yaml:"pshard,omitempty"` // FEC parity shards

	Block string `yaml:"block,omitempty"`
	Key   string `yaml:"key"`

	Smuxbuf      int `yaml:"smuxbuf,omitempty"`
	Streambuf    int `yaml:"streambuf,omitempty"`
	Smuxkalive   int `yaml:"smuxkalive,omitempty"`
	Smuxktimeout int `yaml:"smuxktimeout,omitempty"`
}

type paqetTransport struct {
	Protocol string   `yaml:"protocol"`
	Conn     int      `yaml:"conn"`
	KCP      paqetKCP `yaml:"kcp"`
}

type paqetConf struct {
	Role      string           `yaml:"role"`
	Log       paqetLog         `yaml:"log"`
	Listen    *paqetListen     `yaml:"listen,omitempty"`
	SOCKS5    []paqetSocks5    `yaml:"socks5,omitempty"`
	Forward   []paqetForward   `yaml:"forward,omitempty"`
	Network   paqetNetwork     `yaml:"network"`
	Server    *paqetServerAddr `yaml:"server,omitempty"`
	Transport paqetTransport   `yaml:"transport"`
}

func renderPaqetYAML(c *paqetConf) (string, error) {
	data, err := yaml.Marshal(c)
	if err != nil {
		return "", err
	}
	return "# generated by the rmtunnel wizard for paqet — https://github.com/hanselime/paqet\n" + string(data), nil
}

func loadPaqetConf(path string) (*paqetConf, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c paqetConf
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return &c, nil
}

// --- KCP presets ------------------------------------------------------

// paqetKCPPreset is one named choice in the wizard; apply fills in a
// *paqetKCP already carrying Mode/Block/Key.
type paqetKCPPreset struct {
	name  string
	blurb string
	apply func(k *paqetKCP)
}

func intp(v int) *int    { return &v }
func boolp(v bool) *bool { return &v }

var paqetKCPPresets = []paqetKCPPreset{
	{
		name:  "fast3",
		blurb: "paqet's fastest built-in mode — low latency, good default for most links",
		apply: func(k *paqetKCP) {
			k.Mode = "fast3"
		},
	},
	{
		name:  "gaming (manual, max optimization)",
		blurb: "aggressive manual tuning for lowest ping — large windows/buffers, no congestion control",
		apply: func(k *paqetKCP) {
			// Mirrors the reference config this project was built against:
			// nodelay+no congestion control for lowest latency, large
			// send/receive windows and smux/stream buffers so a single
			// flow isn't left capped well under the link's real capacity.
			k.Mode = "manual"
			k.NoDelay = intp(1)
			k.Interval = intp(10)
			k.Resend = intp(2)
			k.NoCongestion = intp(1)
			k.WDelay = boolp(true)
			k.AckNoDelay = boolp(false)
			k.MTU = 1420
			k.Rcvwnd = 8192
			k.Sndwnd = 8192
			k.Smuxbuf = 128 << 20
			k.Streambuf = 16 << 20
		},
	},
	{
		name:  "normal",
		blurb: "conservative, TCP-like congestion behavior — most compatible, not the fastest",
		apply: func(k *paqetKCP) { k.Mode = "normal" },
	},
	{
		name:  "custom manual",
		blurb: "enter every manual-mode value yourself",
		apply: nil, // handled specially by the wizard — see askPaqetKCP
	},
}

// --- TCP flag helpers ---------------------------------------------------

// paqetTCPFlagChoices mirrors network.tcp.local_flag/remote_flag — cycling
// through more than one pattern varies the traffic's shape; a single entry
// is the common case.
var paqetTCPFlagChoices = []string{"PA", "S", "A", "SA", "F", "R"}

func parsePaqetFlags(raw string) []string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return []string{"PA"}
	}
	var out []string
	for _, p := range strings.Split(raw, ",") {
		if p = strings.ToUpper(strings.TrimSpace(p)); p != "" {
			out = append(out, p)
		}
	}
	if len(out) == 0 {
		return []string{"PA"}
	}
	return out
}

// --- misc helpers --------------------------------------------------------

func parseIntDefault(s string, def int) int {
	v, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		return def
	}
	return v
}
