package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"
)

const sysctlConfPath = "/etc/sysctl.d/99-rmtunnel.conf"
const limitsConfPath = "/etc/security/limits.d/99-rmtunnel.conf"
const systemdLimitsConfPath = "/etc/systemd/system.conf.d/99-rmtunnel-limits.conf"

// sysctlContent covers every kernel/network knob that actually matters for
// a tunnel server: BBR for the high-RTT, often-lossy Iran<->Kharej route;
// buffer ceilings big enough for the tiers in bench.go to actually use (a
// tier's recv_buf/mux_stream_buffer can only ever be as large as these
// allow); backlogs and conntrack sized for a box fielding many concurrent
// connections at once (both real ones and the ordinary port-scan
// background noise any public IP gets — see client.go's pool
// shrink-back fix, which this doesn't replace, it complements: that fix
// stops the *tunnel's own* pool from over-retaining capacity, this stops
// the *kernel* from being the thing that runs out first); fast reuse of
// TIME_WAIT sockets and a wider ephemeral port range for a box that opens
// and closes a lot of short-lived connections quickly; and a lower
// swappiness so a VPS with modest RAM prefers reclaiming page cache over
// swapping a tunnel process's own memory out from under it.
const sysctlContent = `# rmtunnel — generated by the interactive menu ("Optimize")

# BBR: a high-RTT, lossy path benefits far more from this than cubic, the
# kernel default on most distros.
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# Socket buffer ceilings — recv_buf/send_buf/mux_stream_buffer in the
# tunnel's own config can only ever be as large as these allow.
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864

# Larger accept/SYN backlogs and packet backlog for a server taking a heavy
# rate of new connections (many forwarded ports, many concurrent users, or
# just a public IP's own background scanner traffic).
net.core.somaxconn = 8192
net.ipv4.tcp_max_syn_backlog = 8192
net.core.netdev_max_backlog = 16384

# A box proxying many concurrent flows needs the kernel's own connection
# tracking table sized to match, or new connections start getting silently
# dropped long before the tunnel's own pool limits are ever the bottleneck.
net.netfilter.nf_conntrack_max = 262144

# Fast reuse of TIME_WAIT sockets and a wider ephemeral port range — a
# tunnel opens and closes a lot of short-lived local connections (one per
# forwarded flow), and the default range/reuse policy is sized for an
# ordinary client, not a box doing this constantly.
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.ip_local_port_range = 1024 65535

# Detect a dead peer faster than the 2-hour kernel default — this project's
# own heartbeat/keepalive (see config.go) already does this at the
# application layer, but a shorter kernel-level keepalive helps every other
# process on the box too, and costs nothing at idle.
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 5

# Prefer reclaiming page cache over swapping a running process's memory —
# most VPS boxes this runs on have modest RAM and no need to swap a tunnel
# out under light memory pressure.
vm.swappiness = 10

# A high file-descriptor ceiling — see limits.conf/system.conf.d below for
# the per-process/per-service limits that actually use this headroom.
fs.file-max = 2097152
`

// limitsContent raises the *system-wide* open-file ceiling for interactive
// and su'd sessions — the tunnel's own systemd services already set
// LimitNOFILE=1048576 directly on their unit (see service.go), which
// limits.conf never overrides, but a box's default (usually 1024) still
// caps anything else run by hand (a bench session, a manual test) unless
// this is here too.
const limitsContent = `# rmtunnel — generated by the interactive menu ("Optimize")
*    soft nofile 1048576
*    hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
`

// systemdLimitsContent is systemd's own equivalent of limits.conf, which
// (unlike limits.conf) actually applies to services systemd starts
// directly — belt-and-suspenders with each unit's own LimitNOFILE, and the
// one that matters for anything systemd launches that isn't rmtunnel's own
// service (a cron job, a one-shot systemd-run command, ...).
const systemdLimitsContent = `# rmtunnel — generated by the interactive menu ("Optimize")
[Manager]
DefaultLimitNOFILE=1048576
`

func menuTune() {
	sectionHeader("Tune Server")
	if runtime.GOOS != "linux" {
		fmt.Println(dim("this section only applies on Linux — these are Linux kernel settings."))
		pressEnter()
		return
	}

	fmt.Println("This will apply, in order:")
	fmt.Println()
	fmt.Println(bold("1. Kernel/network sysctls") + " (" + sysctlConfPath + "):")
	fmt.Println(dim(sysctlContent))
	fmt.Println(bold("2. Open-file limits") + " (" + limitsConfPath + " and " + systemdLimitsConfPath + "):")
	fmt.Println(dim(limitsContent))
	fmt.Println(dim(systemdLimitsContent))
	if !confirm("apply all of this?", true) {
		return
	}

	applySysctlTuning()
	applyLimitsTuning()
	pressEnter()
}

// applySysctlTuning writes and loads the sysctl block — split out from
// menuTune so Backup & Restore's restore path can reapply a backed-up
// sysctl file the same way, without duplicating the modprobe/sysctl
// --system/verify dance.
func applySysctlTuning() {
	// BBR needs its kernel module loaded; on many modern kernels it's built
	// in and this is a no-op, so a failure here isn't fatal on its own —
	// the sysctl write right after it is the real test.
	run("modprobe", "tcp_bbr")
	// nf_conntrack's sysctl only exists once the module is loaded — harmless
	// no-op if conntrack isn't in use on this box at all (nothing here reads
	// its output, and sysctl --system below just skips a key that can't be
	// set rather than failing the whole file).
	run("modprobe", "nf_conntrack")

	if err := os.WriteFile(sysctlConfPath, []byte(sysctlContent), 0o644); err != nil {
		fmt.Println(red("failed to write " + sysctlConfPath + ": " + err.Error()))
		return
	}
	out, err := run("sysctl", "--system")
	if err != nil {
		fmt.Println(red("sysctl --system failed:"))
		fmt.Println(dim(out))
		return
	}

	cc, _ := run("sysctl", "-n", "net.ipv4.tcp_congestion_control")
	cc = strings.TrimSpace(cc)
	if cc == "bbr" {
		fmt.Println(green("sysctls applied. current congestion control: bbr"))
	} else {
		fmt.Println(yellow("sysctls applied, but current congestion control is \"" + cc + "\", not bbr — this kernel may be missing the bbr module."))
	}
}

// applyLimitsTuning writes the open-file-limit config — a straight file
// write, no daemon to reload for limits.conf (it's read fresh per new
// login/session); systemd's own DefaultLimitNOFILE does need daemon-reexec
// to take effect for the *manager* default, though every unit that sets
// its own LimitNOFILE (this project's own tunnel services already do) is
// unaffected either way.
func applyLimitsTuning() {
	if err := os.MkdirAll("/etc/security/limits.d", 0o755); err == nil {
		if err := os.WriteFile(limitsConfPath, []byte(limitsContent), 0o644); err != nil {
			fmt.Println(red("failed to write " + limitsConfPath + ": " + err.Error()))
		} else {
			fmt.Println(green("open-file limits written: " + limitsConfPath))
		}
	}

	if err := os.MkdirAll("/etc/systemd/system.conf.d", 0o755); err == nil {
		if err := os.WriteFile(systemdLimitsConfPath, []byte(systemdLimitsContent), 0o644); err != nil {
			fmt.Println(red("failed to write " + systemdLimitsConfPath + ": " + err.Error()))
		} else {
			fmt.Println(green("systemd default limit written: " + systemdLimitsConfPath))
			fmt.Println(dim("(takes effect for new services now; " +
				"`systemctl daemon-reexec` applies it system-wide without a reboot)"))
		}
	}
}
