package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"
)

const sysctlContent = `# rmtunnel — generated by the interactive menu
# A high-RTT, lossy path (which the Iran<->Kharej route usually is) benefits
# far more from BBR than from cubic, the kernel default on most distros.
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# Socket buffer ceilings — recv_buf/send_buf in the tunnel's own config can
# only ever be as large as these allow.
net.core.rmem_max = 26214400
net.core.wmem_max = 26214400

# Larger accept/SYN backlogs for a server taking a heavy rate of new
# connections (many forwarded ports, many concurrent users).
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 4096
`

func menuTune() {
	sectionHeader("Tune Server")
	if runtime.GOOS != "linux" {
		fmt.Println(dim("this section only applies on Linux — these are Linux kernel settings."))
		pressEnter()
		return
	}

	fmt.Println("This will apply the following settings to the system:")
	fmt.Println(dim(sysctlContent))
	if !confirm("apply it?", true) {
		return
	}

	// BBR needs its kernel module loaded; on many modern kernels it's built
	// in and this is a no-op, so a failure here isn't fatal on its own —
	// the sysctl write right after it is the real test.
	run("modprobe", "tcp_bbr")

	path := "/etc/sysctl.d/99-rmtunnel.conf"
	if err := os.WriteFile(path, []byte(sysctlContent), 0o644); err != nil {
		fmt.Println(red("failed to write file: " + err.Error()))
		pressEnter()
		return
	}
	out, err := run("sysctl", "--system")
	if err != nil {
		fmt.Println(red("sysctl --system failed:"))
		fmt.Println(dim(out))
		pressEnter()
		return
	}

	cc, _ := run("sysctl", "-n", "net.ipv4.tcp_congestion_control")
	cc = strings.TrimSpace(cc)
	if cc == "bbr" {
		fmt.Println(green("applied. current congestion control: bbr"))
	} else {
		fmt.Println(yellow("applied, but current congestion control is \"" + cc + "\", not bbr — this kernel may be missing the bbr module."))
	}
	pressEnter()
}
